name: hlcm

model_type: segmented_discretechoice

segmentation_col: income_quartile

choosers_fit_filters: null

choosers_predict_filters: null

alts_fit_filters: null

alts_predict_filters: null

interaction_predict_filters: null

choice_column: null

sample_size: 100

estimation_sample_size: 15000

prediction_sample_size: null

default_config:
    model_expression: np.log1p(residential_price) + sum_residential_units + ave_income
        +  autoPeakTotal - 1

models:
    1:
        fit_parameters:
            Coefficient:
                autoPeakTotal: -0.10223779885949648
                ave_income: -0.5725947731722981
                np.log1p(residential_price): 0.2617883365575034
                sum_residential_units: 0.6048473486420561
            Std. Error:
                autoPeakTotal: 0.0122104067821399
                ave_income: 0.011750701918235138
                np.log1p(residential_price): 0.021066240966816738
                sum_residential_units: 0.010350599652213988
            T-Score:
                autoPeakTotal: -8.373005149102747
                ave_income: -48.72855912409165
                np.log1p(residential_price): 12.426912659447353
                sum_residential_units: 58.43597172775198
        fitted: true
        log_likelihoods:
            convergence: -61140.93927470973
            'null': -64306.59647715164
            ratio: 0.04922756569097353
        name: 1
    2:
        fit_parameters:
            Coefficient:
                autoPeakTotal: -0.07507062911914548
                ave_income: -0.36666428998768025
                np.log1p(residential_price): 0.17552355526665744
                sum_residential_units: 0.42708810730157276
            Std. Error:
                autoPeakTotal: 0.012619996841923498
                ave_income: 0.012547192358443924
                np.log1p(residential_price): 0.023572060819275466
                sum_residential_units: 0.01060976518108548
            T-Score:
                autoPeakTotal: -5.948545792797796
                ave_income: -29.222815711510552
                np.log1p(residential_price): 7.446254131633982
                sum_residential_units: 40.25424691424486
        fitted: true
        log_likelihoods:
            convergence: -66369.04354354221
            'null': -67972.31194519628
            ratio: 0.023587080618160172
        name: 2
    3:
        fit_parameters:
            Coefficient:
                autoPeakTotal: -0.005650969198108769
                ave_income: -0.04080435785945824
                np.log1p(residential_price): 0.09593674858625535
                sum_residential_units: 0.2398833136060988
            Std. Error:
                autoPeakTotal: 0.01286359458817556
                ave_income: 0.013263927273320292
                np.log1p(residential_price): 0.026509327734333496
                sum_residential_units: 0.010440600770801632
            T-Score:
                autoPeakTotal: -0.43929938551571257
                ave_income: -3.076340590432376
                np.log1p(residential_price): 3.618980818664937
                sum_residential_units: 22.976006732961256
        fitted: true
        log_likelihoods:
            convergence: -67521.16300293064
            'null': -68032.17915761407
            ratio: 0.007511388889947623
        name: 3
    4:
        fit_parameters:
            Coefficient:
                autoPeakTotal: 0.06612526738980411
                ave_income: 1.4668279279140652
                np.log1p(residential_price): 0.10031127141298858
                sum_residential_units: 0.23607897022825117
            Std. Error:
                autoPeakTotal: 0.013609481559141821
                ave_income: 0.013893356338103744
                np.log1p(residential_price): 0.02671570119154099
                sum_residential_units: 0.0096994006883136
            T-Score:
                autoPeakTotal: 4.858764612189518
                ave_income: 105.57765108861143
                np.log1p(residential_price): 3.754768429763326
                sum_residential_units: 24.33954197940217
        fitted: true
        log_likelihoods:
            convergence: -66395.70533051081
            'null': -68165.72909300758
            ratio: 0.025966475911695874
        name: 4

fitted: true

choice_mode: aggregate

remove_alts: true

probability_mode: single_chooser
