name: hlcm

model_type: segmented_discretechoice

segmentation_col: income_quartile

choosers_fit_filters: null

choosers_predict_filters: null

alts_fit_filters: null

alts_predict_filters: null

interaction_predict_filters: null

choice_column: null

sample_size: 100

estimation_sample_size: 15000

prediction_sample_size: null

default_config:
    model_expression: np.log1p(residential_price) + sum_residential_units + ave_income
        +  autoPeakTotal - 1

models:
    1:
        fit_parameters:
            Coefficient:
                autoPeakTotal: -0.06169633280009745
                ave_income: -0.5610139416175929
                np.log1p(residential_price): 0.26187958573102443
                sum_residential_units: 0.6006641680071897
            Std. Error:
                autoPeakTotal: 0.012509313542045743
                ave_income: 0.012123027166229107
                np.log1p(residential_price): 0.021699759119927057
                sum_residential_units: 0.010580287118953889
            T-Score:
                autoPeakTotal: -4.932031849127973
                ave_income: -46.27672065112574
                np.log1p(residential_price): 12.068317638168544
                sum_residential_units: 56.772010178357
        fitted: true
        log_likelihoods:
            convergence: -60847.91554999649
            'null': -64103.96898896805
            ratio: 0.05079332044996954
        name: 1
    2:
        fit_parameters:
            Coefficient:
                autoPeakTotal: -0.0898462847859181
                ave_income: -0.3846715005696697
                np.log1p(residential_price): 0.18760903513820446
                sum_residential_units: 0.45459568003690043
            Std. Error:
                autoPeakTotal: 0.012768749892762946
                ave_income: 0.012491136617900528
                np.log1p(residential_price): 0.023688495593981104
                sum_residential_units: 0.0106707371412216
            T-Score:
                autoPeakTotal: -7.036419817169499
                ave_income: -30.79555626814721
                np.log1p(residential_price): 7.919837475279483
                sum_residential_units: 42.60208774900604
        fitted: true
        log_likelihoods:
            convergence: -66132.54749146024
            'null': -67898.62922222055
            ratio: 0.02601056532349466
        name: 2
    3:
        fit_parameters:
            Coefficient:
                autoPeakTotal: -0.022446839668893374
                ave_income: -0.021368959016446684
                np.log1p(residential_price): 0.10153981291071038
                sum_residential_units: 0.25452567147109073
            Std. Error:
                autoPeakTotal: 0.012934875005932912
                ave_income: 0.013123272832064013
                np.log1p(residential_price): 0.026294898549351964
                sum_residential_units: 0.010488533774385023
            T-Score:
                autoPeakTotal: -1.7353735276604958
                ave_income: -1.6283254406047274
                np.log1p(residential_price): 3.8615784244283695
                sum_residential_units: 24.26704026950749
        fitted: true
        log_likelihoods:
            convergence: -67541.62592246188
            'null': -68078.2308594739
            ratio: 0.007882180988511123
        name: 3
    4:
        fit_parameters:
            Coefficient:
                autoPeakTotal: 0.051958136171733706
                ave_income: 1.466643441880954
                np.log1p(residential_price): 0.1031379033225841
                sum_residential_units: 0.24741741882097387
            Std. Error:
                autoPeakTotal: 0.013722664672073056
                ave_income: 0.013653533748759043
                np.log1p(residential_price): 0.026324861283726443
                sum_residential_units: 0.009771850122149576
            T-Score:
                autoPeakTotal: 3.7863007960453565
                ave_income: 107.41859718289089
                np.log1p(residential_price): 3.9178897169096234
                sum_residential_units: 25.319403769830632
        fitted: true
        log_likelihoods:
            convergence: -66467.67173123434
            'null': -68225.59630542537
            ratio: 0.025766349718972514
        name: 4

fitted: true

choice_mode: aggregate

remove_alts: true

probability_mode: single_chooser
